config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "themes#index"

  resources :themes, only: [:new, :create] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :theme
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?
  
  def was_attached?
    self.image.attached?
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :theme_users
  has_many :users, through: :theme_users
  has_many :messages
  
  validates :theme_name, presence: true

  def self.search(search)
    if search != ""
      Theme.where('theme_name LIKE(?)', "%#{search}%")
    else
      Theme.all
    end
  end
end

app/models/theme_user.rb
class ThemeUser < ApplicationRecord
  belongs_to :theme
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :theme_users
  has_many :themes, through: :theme_users
  has_many :messages 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @theme = Theme.find(params[:theme_id])
    @message = Message.new
    @messages = @theme.messages.includes(:user)
    @themes = Theme.search(params[:keyword])
  end

  def create
    @themes = Theme.find(params[:theme_id])
    @message = @themes.messages.new(message_params)
    if @message.save
      redirect_to theme_messages_path
    else
      @messages = @theme.messages.includes(:user)
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!

  def index
    @theme = Theme.order('created_at DESC')
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(root_params)
    if @theme.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    @themes = Theme.search(params[:keyword])
  end

  private
  def root_params
    params.require(:theme).permit(:theme_name, :theme_content, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Talk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/messages/_left_bar.html.erb
<div class="left_bar">
  <div class="top_left_bar">
    <div class="top-left_title">テーマ一へ戻る</div>
  </div>
  <div class="message_top_left_bar">
    <%= link_to image_tag("back_botton.png", class: :message_left_logo), root_path %>
  </div>
</div>

app/views/messages/_main_chat.html.erb
<div class="main_chat">
  <div class="theme_main">
    <div class="top_theme_main">
      <div class="top-theme_title">
        <%= @theme.theme_name %>
      </div>
      <div class="top-content_title">
        <%= @theme.theme_content %>
      </div>
    </div>
  </div>

  <div class="main_form">
    <div class="chat_form">
      <div class="message">
        <% @messages.each do |message| %>
        <div class="upper-message">
          <div class="right_pic"></div>
            <div class="message-user">
              <%= message.user.nickname %>
            </div>
            <div class="message-date">
              <%= message.created_at %>
            </div>
        </div>
        <div class="lower-message">
          <div class="message-content">
            <%= message.content %>
          </div>
          <div><%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %></div>
        </div>
        <% end %>
      </div>

      <%= form_with model: [@theme, @message], class: 'form', local: true do |f| %>
      <div class="main-input">
        <div class="form-input">
          <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
          <label class="form-image">
          <span class="image-file">画像</span>
          <%= f.file_field :image, class: 'hidden' %>
          </label>
        </div>
          <%= f.submit '送信', class: 'form-submit' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_right_bar.html.erb
<div class="right_bar">
  <div class="top_right_bar">
    <div class="top-right_title">参加ユーザー</div>
  </div>

  <div class="right_main_user">
    <div class="right_form">
      <% .each do |a| %>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to , "/" %></div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_top_header.html.erb
<div class="header">
  <div class="top-header">
    <div class="nav">
      <div class="nav_left">
        <%= link_to image_tag("talk2.png", class: :logo), root_path %>
          
      </div>

      <% if user_signed_in? %>
      <div class="user_nav">
        <div class="top_user_name"><strong><%= link_to current_user.nickname, "/" %></strong></div>
          <div class="grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </div>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path %>
          <%= link_to "新規登録", new_user_registration_path %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<%= render "top_header" %>

<div class="wrapper">
  <%= render "left_bar" %>
  <%= render "main_chat" %>
  <div></div>
</div>

app/views/shared/_right_bar.html.erb
<div class="right_bar">
  <div class="top_right_bar">
    <div class="top-right_title">参加ユーザー</div>
  </div>

  <div class="right_main_user">
    <div class="right_form">
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
      <div class="right_user_form">
        <div class="right_pic"></div>
        <div class="right_user"><%= link_to "ユーザー名", "/" %></div>
      </div>
    </div>
  </div>
</div>

app/views/themes/index.html.erb
<%= render "messages/top_header" %>

<div class="theme_wrapper">
  <div class="new_left_bar">
    <div class="top_left_bar">
      <div class="top-left_title">テーマ一覧</div>
    </div>

    <div class="new_theme_form">
      <div class="new_theme"><%= link_to "新規作成", new_theme_path %></div>
    </div>

    <div class="search-main">
      <%= form_with(url: search_themes_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "テーマを探す", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
    </div>

    <div class="left_main_user">
      <div class="left_user_form">
        <% @theme.each do |theme| %>
        <div class="left_theme">
          <%= link_to theme.theme_name, theme_messages_path(theme) %>
        </div>
        <% end %>
      </div>
      <% if @theme.empty? %>
        <div class="left_theme">
          <%= "ここにテーマが表示されます。" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/themes/new.html.erb
<div class='chat-room-form'>
  <h1>新規テーマ名</h1>
  <%= form_with model: @theme, local: true do |f| %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field-theme'>
        <%= f.label :theme_name, :テーマ名, class: 'chat-room-form__label'%>
        <%= f.text_field :theme_name, class: 'chat__room_name chat-room-form__input', placeholder: '話したいテーマを入力してください'%>
      </div>

      <div class='chat-room-form__field--right'>
        <%= f.label :theme_content, :詳細内容（任意）, class: 'chat-room-form__label'%>
        <%= f.text_area :theme_content, class: 'chat__room_name chat-room-form__text', placeholder: '詳細説明(任意)'%>
      </div>

      <div class='chat-room-form__field--right'>
        <%= f.submit "作成する", class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/themes/search.html.erb
<div class="theme_wrapper">
  <div class="new_left_bar">
    <div class="top_left_bar">
    <div class="top-left_title">テーマ一覧</div>
    </div>

    <div class="new_theme_form">
      <div class="new_theme"><%= link_to "新規作成", new_theme_path %></div>
    </div>

    <div class="search-main">
      <%= form_with(url: search_themes_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "テーマを探す", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
    </div>

    <div class="left_main_user">
      <div class="left_user_form">
        <div class="search-result">検索結果</div>
        <% @themes.each do |theme| %>
          <div class="left_theme">
            <%= link_to theme.theme_name, theme_messages_path(theme) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="theme_wrapper">
  <div class="new_left_bar">
    <div class="top_left_bar">
      <div class="top-left_title">テーマ一覧</div>
    </div>

    <div class="left_main_user">
      <div class="left_user_form">
        <%  %>
        <div class="left_theme">
          <%= link_to "", theme_messages_path(theme) %>
        </div>
        <% end %>
      </div>
      <% if "" %>
        <div class="left_theme">
          <%= "ここにテーマが表示されます。" %>
        </div>
      <% end %>
    </div>
  </div>
</div>